### PR TITLE
Scala 2.12.0-RC2

### PR DESCRIPTION
**Pull request by larsrh**

### CODE REVIEW

**Comment by larsrh** [comment]
Released `0.4.2` based on 49dfa98.

**Comment by larsrh** [comment]
Missing dependency chain:

* [ ] ScalaCheck (rickynils/scalacheck#291)
* [ ] ScalaTest (scalatest/scalatest#989)
* [ ] scodec-bits (scodec/scodec-bits#65)

**Comment by larsrh** [comment]
Released `0.4.2` for Scala 2.12.

**Comment by lihaoyi** [comment]
Thanks lars!

**Pull request merged**
