### PR TITLE
Add Opaque combinator

### PR DESCRIPTION
**Pull request by stanch**
As discussed here: https://gitter.im/lihaoyi/fastparse?at=564e1994b0853133165607bc.

### CODE REVIEW

**Comment by lihaoyi** [comment]
Can we make an un-specified `msg` (`null`? `""`? Idunno) return the `toString` of the parser? I imagine that'll be useful in a bunch of cases where your `P(...) ` parser already has a reasonable name, and you just want to hide the insides. In general, FastParse's methods are chock-full of helpers of various sorts, so it would fit right in.

Also, could we add a line to the readme, `sect.ref`-ed to the header in the docs? =)

**Comment by lihaoyi** [comment]
And by "readme" of course I mean "changelog"...

**Comment by stanch** [comment]
You can already do this: `parser.opaque()`, which will use `parser.toString`. I was trying to reduce the number of places where there are defaults.

I will update the changelog.

**Comment by lihaoyi** [comment]
Merged. Thanks @stanch!

**Pull request merged**
