### PR TITLE
2.13.0-M5 support for Fastparse 1.x

### PR DESCRIPTION
**Pull request by thesamet**
Based on @alexarchambault 's  #194 . This updates various SBT plugins and SBT itself. My intent is to make a release of this from the 1.x branch.

### CODE REVIEW

**Comment by lihaoyi** [comment]
sounds good

**Comment by thesamet** [comment]
Any hints on how to go about the scalaparse failure for 2.13.0-M5:

```
 for [info] CompilationUnit:1:1 / Body:1:1 / TopStatSeq:1:1 / TopStat:1:1 / Tmpl:1:1 / ClsDef:1:1 / DefTmpl:1:12 / TmplBody:1:12 / }:2:12 / (";" | Newline.rep(1) | "}"):2:12 ..."1 = - 1\n}\n"
[info]       scalaparse.TestUtil$.$anonfun$check$2(TestUtil.scala:67)
[info]       scalaparse.TestUtil$.$anonfun$check$2$adapted(TestUtil.scala:62)
[info]       scala.collection.immutable.List.foreach(List.scala:302)
[info]       scalaparse.TestUtil$.check(TestUtil.scala:62)
[info]       scalaparse.ProjectTests$.$anonfun$tests$7(ProjectTests.scala:34)
[info]       scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]       scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[info]       scala.util.Success.$anonfun$map$1(Try.scala:261)
[info]       scala.util.Success.map(Try.scala:209)
[info]       scala.concurrent.impl.Promise$Transformation.doMap(Promise.scala:420)
[info]       scala.concurrent.impl.Promise$Transformation.run(Promise.scala:402)
[info]       java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[info]       java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[info]       java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[info]       java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[info]       java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by olafurpg** [comment]
Thank you for this contribution! Support for 2.13.0-RC1 has been merged in #220, we're working on cutting a new release.

**Comment by olafurpg** [comment]
I'm sorry, I didn't realize this was for the 1.x branch.

**Pull request closed without merging**
