### PR TITLE
First pass cleanup of GSOC code

### PR DESCRIPTION
**Pull request by lihaoyi**
- Indent a bunch of parens the way everything else is indented
- Remove one dead statement
- change a bunch of `URL.getPath` to `URL.toURI.getPath` in order to make it work in folders with funny characters (e.g. spaces)

This should make the codebase more consistent and easier for me to work with...

Review by @vovapolu

### CODE REVIEW

**Comment by vovapolu** [comment]
Is there going to be more commits?

**Comment by lihaoyi** [comment]
Yeah but let's review/merge this first and I'll send more later

**Comment by vovapolu** [comment]
@lihaoyi tests failed, perhaps you forgot the `)` or `}` somewhere.

**Comment by lihaoyi** [comment]
oops, will take a look when i'm back at a computer

**Pull request merged**
