### PR TITLE
be Scala 2.13 friendly

### PR DESCRIPTION
**Pull request by SethTisue**
for the Scala 2.13 community build (yes, there is one already)

### CODE REVIEW

**Comment by lihaoyi** [comment]
Huh seems to have broken the build for 2.12; seems we're including multiple `scala-2.1X/` folders and it's resulting in duplicate `Compat` objects

**Comment by SethTisue** [comment]
fixed version pushed, let's see if Travis agrees

**Comment by SethTisue** [comment]
Travis agrees.

**Comment by lihaoyi** [comment]
Looks good to me thanks!

**Pull request merged**
