### PR TITLE
Added support for literal types.

### PR DESCRIPTION
**Pull request by milessabin**
Before I go any further with this, I'd like to know how you want to handle this feature being enabled/disabled ...

### CODE REVIEW

**Comment by lihaoyi** [comment]
I'd be perfectly happy having be non-disable-able to be honest. ScalaParse is already a "sloppy" parser and accepts more than the Scalac parser does, and this shouldn't cause existing "good" code to parse in a different way AFAICT

**Comment by milessabin** [comment]
Okey doke ... I've added a few more tests, and removed the failing tests which are now expected to pass.

**Comment by lihaoyi** [comment]
Looks good to me, thanks @milessabin! This will go out in 0.4.0 after https://github.com/lihaoyi/fastparse/pull/122 lands and I'll publish a corresponding new version of Ammonite. Realistically probably in a week or so

**Comment by milessabin** [comment]
Awesome! Thanks :-)

**Pull request merged**
