### PR TITLE
Port to Scala Native

### PR DESCRIPTION
**Pull request by olafurpg**
Opening this PR just to show progress, currently waiting for new release of scodec bits and Scala Native to fix remaining issues. Tests pass for fastparse/scalaparse/cssparse when using a local publish of scala native with https://github.com/scala-native/scala-native/pull/902.

### CODE REVIEW

**Comment by olafurpg** [comment]
Now blocked by https://github.com/lihaoyi/fastparse/pull/160 for the fastparseByte module.

Also hit linking errors for classparseNative/test

```
[info] Linking (1939 ms)
[error] cannot link: @java.lang.Class::getDeclaredFields_scala.scalanative.runtime.ObjectArray
[error] cannot link: @java.lang.Class::getMethod_java.lang.String_scala.scalanative.runtime.ObjectArray_java.lang.reflect.Method
[error] cannot link: @java.lang.Class::getMethods_scala.scalanative.runtime.ObjectArray
[error] cannot link: @java.lang.reflect.Field::getName_java.lang.String
[error] cannot link: @java.lang.reflect.Field::getType_java.lang.Class
[error] cannot link: @java.lang.reflect.Method
[error] cannot link: @java.lang.reflect.Method::getDeclaringClass_java.lang.Class
[error] cannot link: @java.lang.reflect.Method::getName_java.lang.String
[error] cannot link: @java.lang.reflect.Method::getParameterTypes_scala.scalanative.runtime.ObjectArray
[error] cannot link: @java.lang.reflect.Method::getReturnType_java.lang.Class
[error] cannot link: @java.lang.reflect.Method::invoke_java.lang.Object_scala.scalanative.runtime.ObjectArray_java.lang.Object
[error] unable to link
```

**Comment by lihaoyi** [comment]
@olafurpg 
https://github.com/lihaoyi/fastparse/blob/3da22d6480746b1582353b4b157c7dbba2686ff3/classparse/shared/src/test/scala/classparse/TestUtils.scala#L26 is using Java reflection to load bytecode, in order to feed it through the parser as a sanity check (here too https://github.com/lihaoyi/fastparse/blob/3da22d6480746b1582353b4b157c7dbba2686ff3/classparse/jvm/src/test/scala/classparse/ProjectTests.scala#L29)

We could probably get away with using direct filesystem access rather than going through classloaders and java-reflection, or even just disabling that entire suite of tests of Scala-Native. Apart from these bulk classloader-load-classfile-and-parse tests, that logic is all reasonable covered by unit tests in https://github.com/lihaoyi/fastparse/blob/3da22d6480746b1582353b4b157c7dbba2686ff3/classparse/shared/src/test/scala/classparse/ClassTests.scala so I'm not too afraid of it getting silently broken in Scala-Native

**Comment by olafurpg** [comment]
I linked the wrong issue above, I meant fastparseByte is blocked by https://github.com/scala-native/scala-native/issues/925 I disabled NativePlatform for fastparseByte and its dependents classparse and perftests. 

The only remaining issue is that the following warning prints when loading sbt

```
Project defines platforms: js, jvm
project fastparse

  discards: native
Project defines platforms: js, jvm
project fastparse

  discards: native
project pythonparse

  discards: native
project scalaparse

  discards: native
project cssparse

  discards: native
```
even if native is enabled for those projects. I cancelled all the non-native builds on Travis to see if the CI can reproduce the warnings.

**Comment by olafurpg** [comment]
The CI failures seemt to be unrelated to this PR, https://travis-ci.org/lihaoyi/fastparse/jobs/263232670#L1528 twitter/scalading is failing in ProjectTests

We will have to wait until https://github.com/scala-native/scala-native/issues/925 is fixed to cross-build fastparseByte to native. utils/fastparse/scalaparse/pythonparse/cssparse are cross-built.

This PR is ready for review. Would be nice to merge #159 first. Only annoyance is the warnings on sbt load that are printed by sbt-crossproject https://github.com/scala-native/sbt-crossproject/issues/52 @densh mentioned the warning might be spurious in this case.

**Comment by lihaoyi** [comment]
Looks fine to me. Feel free to take Scalding out of the test suite if it's misbehaving to make things green again

**Comment by olafurpg** [comment]
CI is green! 🎉 A sanity check in the logs shows native binaries are running https://travis-ci.org/lihaoyi/fastparse/jobs/264040997#L2488

I'll go ahead and merge this. Note that sbt still prints that annoying warning on startup, https://travis-ci.org/lihaoyi/fastparse/jobs/264040984#L865 I hope it doesn't bug you too much before it gets fixed in sbt-crossproject @lihaoyi 😜

**Comment by lihaoyi** [comment]
Yeah I've never been very strict about warnings. You have my publishing credentials already IIRC, so feel free to publish when you're ready

**Comment by olafurpg** [comment]
fastparse 0.4.4 has been released with scala native support! changelog pending in #163

**Pull request merged**
